# WARNING: This file is auto-generated by formula.py.
# Manual changes to this file will be overwritten the next time the file is generated.
# If you need to modify the contents, please update the source template or the generating script.

class Beam < Formula
  desc "The open-source serverless GPU container runtime."
  homepage "https://docs.beam.cloud/v2"
  license "AGPL-3.0"
  version "0.2.97"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/beam-cloud/beam-client/releases/download/cli-0.2.97/beam-0.2.97-darwin-amd64.tar.gz"
    sha256 "1f277dd2f48c223b49a36c1df15cbee63bc51cef6c58d1fb7fd991ff18fd50f4"
  elsif OS.mac? && Hardware::CPU.arm?
    url "https://github.com/beam-cloud/beam-client/releases/download/cli-0.2.97/beam-0.2.97-darwin-arm64.tar.gz"
    sha256 "a6a1a80a18da86d979747a2c332077d9473332bddb3a070c273dd0addcdb361a"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/beam-cloud/beam-client/releases/download/cli-0.2.97/beam-0.2.97-linux-amd64.tar.gz"
    sha256 "c2d71f4a4bcf2434de3a38a0061e5fdda073df5d231bbb05a8b820d1b9c0efd7"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/beam-cloud/beam-client/releases/download/cli-0.2.97/beam-0.2.97-linux-arm64.tar.gz"
    sha256 "5daf2d6f6799e8ea020debaf2575a5d9b444589d98b77d365b0907f68fa34382"
  else
    odie "Unsupported platform or architecture"
  end

  def install
    bin.install "beam"
  end

  test do
    system "#{bin}/beam", "--version"
  end
end
