# WARNING: This file is auto-generated by formula.py.
# Manual changes to this file will be overwritten the next time the file is generated.
# If you need to modify the contents, please update the source template or the generating script.

class Beam < Formula
  desc "The open-source serverless GPU container runtime."
  homepage "https://docs.beam.cloud/v2"
  license "AGPL-3.0"
  version "0.2.137"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/beam-cloud/beam-client/releases/download/cli-0.2.137/beam-0.2.137-darwin-amd64.tar.gz"
    sha256 "3c2a2505cff2802e18ea5c0fb56b83359f6881d1a77c37c4bff2e7ff6ca222b8"
  elsif OS.mac? && Hardware::CPU.arm?
    url "https://github.com/beam-cloud/beam-client/releases/download/cli-0.2.137/beam-0.2.137-darwin-arm64.tar.gz"
    sha256 "206784acc086b8465ae1c15a8afbca9856d3a4070638d90aa6cb654b6e03d8ff"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/beam-cloud/beam-client/releases/download/cli-0.2.137/beam-0.2.137-linux-amd64.tar.gz"
    sha256 "35e6a6a4b6844ddb99c0c6f32f7f98dab9780750e74ce08690bf0978f8a649e4"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/beam-cloud/beam-client/releases/download/cli-0.2.137/beam-0.2.137-linux-arm64.tar.gz"
    sha256 "30194deeef49e7c1ecd78ba47fc715e7d2da03d03c1cc17923f8628febefc9fa"
  else
    odie "Unsupported platform or architecture"
  end

  def install
    bin.install "beam"
  end

  test do
    system "#{bin}/beam", "--version"
  end
end
