# WARNING: This file is auto-generated by formula.py.
# Manual changes to this file will be overwritten the next time the file is generated.
# If you need to modify the contents, please update the source template or the generating script.

class Beam < Formula
  desc "The open-source serverless GPU container runtime."
  homepage "https://docs.beam.cloud/v2"
  license "AGPL-3.0"
  version "0.2.30"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/beam-cloud/beam-client/releases/download/cli-0.2.30/beam-0.2.30-darwin-amd64.tar.gz"
    sha256 "6a4a91ed2792a6a5b6e87b7685306f9ef9c432116611de470feb27c1e4b73cbd"
  elsif OS.mac? && Hardware::CPU.arm?
    url "https://github.com/beam-cloud/beam-client/releases/download/cli-0.2.30/beam-0.2.30-darwin-arm64.tar.gz"
    sha256 "a6e32a31b4bed0f92c8196aeb625046a7dc7d6aa5e5459b0d23ac7ebae089ee4"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/beam-cloud/beam-client/releases/download/cli-0.2.30/beam-0.2.30-linux-amd64.tar.gz"
    sha256 "7d6a3bec8e34b099c4fd2f9c055c3f8dca6487653e661d67a39cdc25e315cd97"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/beam-cloud/beam-client/releases/download/cli-0.2.30/beam-0.2.30-linux-arm64.tar.gz"
    sha256 "dfce5b70abb188e083cb549a0c353c31b89259865015ebb82731d8be930d656d"
  else
    odie "Unsupported platform or architecture"
  end

  def install
    bin.install "beam"
  end

  test do
    system "#{bin}/beam", "--version"
  end
end
