# WARNING: This file is auto-generated by formula.py.
# Manual changes to this file will be overwritten the next time the file is generated.
# If you need to modify the contents, please update the source template or the generating script.

class Beam < Formula
  desc "The open-source serverless GPU container runtime."
  homepage "https://docs.beam.cloud/v2"
  license "AGPL-3.0"
  version "0.2.76"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/beam-cloud/beam-client/releases/download/cli-0.2.76/beam-0.2.76-darwin-amd64.tar.gz"
    sha256 "901bd74d18a696a0ce7472d92c6435706f9c79791564455e555dff43f7625fc5"
  elsif OS.mac? && Hardware::CPU.arm?
    url "https://github.com/beam-cloud/beam-client/releases/download/cli-0.2.76/beam-0.2.76-darwin-arm64.tar.gz"
    sha256 "871de1ac8ca6ccad192401cc9049d39b86d5a729435c000154dfa19c0f6cfa9e"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/beam-cloud/beam-client/releases/download/cli-0.2.76/beam-0.2.76-linux-amd64.tar.gz"
    sha256 "227ba1e03f31aac3daccdb22fb96bff8ff1bfe1f109057e6b3db615e44420ee0"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/beam-cloud/beam-client/releases/download/cli-0.2.76/beam-0.2.76-linux-arm64.tar.gz"
    sha256 "fe702da3a97e26a36af9ebab766cd39fcd22ad55800a856667e35ddad692a3d6"
  else
    odie "Unsupported platform or architecture"
  end

  def install
    bin.install "beam"
  end

  test do
    system "#{bin}/beam", "--version"
  end
end
