# WARNING: This file is auto-generated by formula.py.
# Manual changes to this file will be overwritten the next time the file is generated.
# If you need to modify the contents, please update the source template or the generating script.

class Beam < Formula
  desc "The open-source serverless GPU container runtime."
  homepage "https://docs.beam.cloud/v2"
  license "AGPL-3.0"
  version "0.2.31"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/beam-cloud/beam-client/releases/download/cli-0.2.31/beam-0.2.31-darwin-amd64.tar.gz"
    sha256 "3721fbbf1189c2bee0511a98c9108f6a531dd6b45057c665d050ad6a63707796"
  elsif OS.mac? && Hardware::CPU.arm?
    url "https://github.com/beam-cloud/beam-client/releases/download/cli-0.2.31/beam-0.2.31-darwin-arm64.tar.gz"
    sha256 "076f2c2f6e214379528c822c5046edc5ca3619eaf0cd704b4c7a9f6d62b4bc72"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/beam-cloud/beam-client/releases/download/cli-0.2.31/beam-0.2.31-linux-amd64.tar.gz"
    sha256 "3d6cc8e88ac1be07fa6946eb63419440b5ecd3ba1a61fce28e33f327c4a31d3e"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/beam-cloud/beam-client/releases/download/cli-0.2.31/beam-0.2.31-linux-arm64.tar.gz"
    sha256 "2be1873741aeb083f8b624653d791d0d29b88466dc04cd102ec5445f91795439"
  else
    odie "Unsupported platform or architecture"
  end

  def install
    bin.install "beam"
  end

  test do
    system "#{bin}/beam", "--version"
  end
end
