# WARNING: This file is auto-generated by formula.py.
# Manual changes to this file will be overwritten the next time the file is generated.
# If you need to modify the contents, please update the source template or the generating script.

class Beta9 < Formula
  desc "The open-source serverless GPU container runtime."
  homepage "https://docs.beam.cloud/v2"
  license "AGPL-3.0"
  version "0.1.42"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/beam-cloud/beta9/releases/download/cli-0.1.42/beta9-0.1.42-darwin-amd64.tar.gz"
    sha256 "92aff7bd15e4a0c42abd3936f5639daee9e683953990ed93c43a5db386913ae1"
  elsif OS.mac? && Hardware::CPU.arm?
    url "https://github.com/beam-cloud/beta9/releases/download/cli-0.1.42/beta9-0.1.42-darwin-arm64.tar.gz"
    sha256 "f7e91e7916908c933db49d9b16f5c34f5a44a36a1fbbed2ba1d21df492a445c7"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/beam-cloud/beta9/releases/download/cli-0.1.42/beta9-0.1.42-linux-amd64.tar.gz"
    sha256 "169fceca6fde6ccf3e9990b4e6ef2ba387807b09dc31b7f0406185a10771a181"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/beam-cloud/beta9/releases/download/cli-0.1.42/beta9-0.1.42-linux-arm64.tar.gz"
    sha256 "404e3e84bc8714e4632a660678b49dd99ca23c9d7ded610d1f9f58e79bb2d365"
  else
    odie "Unsupported platform or architecture"
  end

  def install
    bin.install "beta9"
  end

  test do
    system "#{bin}/beta9", "--version"
  end
end
