# WARNING: This file is auto-generated by formula.py.
# Manual changes to this file will be overwritten the next time the file is generated.
# If you need to modify the contents, please update the source template or the generating script.

class Beta9 < Formula
  desc "The open-source serverless GPU container runtime."
  homepage "https://docs.beam.cloud/v2"
  license "AGPL-3.0"
  version "0.1.36"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/beam-cloud/beta9/releases/download/cli-0.1.36/beta9-0.1.36-darwin-amd64.tar.gz"
    sha256 "7634e220a7825f8fcc835155df9c6edfc48f00f2d3f8381e4d22acb056157546"
  elsif OS.mac? && Hardware::CPU.arm?
    url "https://github.com/beam-cloud/beta9/releases/download/cli-0.1.36/beta9-0.1.36-darwin-arm64.tar.gz"
    sha256 "b0e753f8ef3ecb2eb8fcdd3e750485ece624496405ff7c574366c93c377b1ce5"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/beam-cloud/beta9/releases/download/cli-0.1.36/beta9-0.1.36-linux-amd64.tar.gz"
    sha256 "7c3727f4c619ea70e4d83fad8cce9f7da40ba34793de8f949f68ac2d0c6a0b90"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/beam-cloud/beta9/releases/download/cli-0.1.36/beta9-0.1.36-linux-arm64.tar.gz"
    sha256 "7c3727f4c619ea70e4d83fad8cce9f7da40ba34793de8f949f68ac2d0c6a0b90"
  else
    odie "Unsupported platform or architecture"
  end

  def install
    bin.install "beta9"
  end

  test do
    system "#{bin}/beta9", "--version"
  end
end
