# WARNING: This file is auto-generated by formula.py.
# Manual changes to this file will be overwritten the next time the file is generated.
# If you need to modify the contents, please update the source template or the generating script.

class Beta9 < Formula
  desc "The open-source serverless GPU container runtime."
  homepage "https://docs.beam.cloud/v2"
  license "AGPL-3.0"
  version "0.1.37"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/beam-cloud/beta9/releases/download/cli-0.1.37/beta9-0.1.37-darwin-amd64.tar.gz"
    sha256 "2e96b26f32d69b280c402108428ab63e07d95623fc5040c751bf395b661f9d54"
  elsif OS.mac? && Hardware::CPU.arm?
    url "https://github.com/beam-cloud/beta9/releases/download/cli-0.1.37/beta9-0.1.37-darwin-arm64.tar.gz"
    sha256 "472328b45501597ce34b8e4966b1f591a632fcfa65e27dd594f634b0f69803f5"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/beam-cloud/beta9/releases/download/cli-0.1.37/beta9-0.1.37-linux-amd64.tar.gz"
    sha256 "e29b73860de16d1a72bfa41fb9ee01389eba865678a0c47042a8d756b70f882c"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/beam-cloud/beta9/releases/download/cli-0.1.37/beta9-0.1.37-linux-arm64.tar.gz"
    sha256 "7caa5ce9fb83627770fce18681415b3588cb7bee28f8bd8d37cdbeed019fdc61"
  else
    odie "Unsupported platform or architecture"
  end

  def install
    bin.install "beta9"
  end

  test do
    system "#{bin}/beta9", "--version"
  end
end
