# WARNING: This file is auto-generated by formula.py.
# Manual changes to this file will be overwritten the next time the file is generated.
# If you need to modify the contents, please update the source template or the generating script.

class Beta9 < Formula
  desc "The open-source serverless GPU container runtime."
  homepage "https://docs.beam.cloud/v2"
  license "AGPL-3.0"
  version "cli-0.1.36"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/beam-cloud/beta9/releases/download/cli-0.1.36/beta9-cli-0.1.36-darwin-amd64.tar.gz"
    sha256 "50881ca35c0a7af543e5361e75f15fe49a5ac9cc8eaef17a3e5d5dd57245bbee"
  elsif OS.mac? && Hardware::CPU.arm?
    url "https://github.com/beam-cloud/beta9/releases/download/cli-0.1.36/beta9-cli-0.1.36-darwin-arm64.tar.gz"
    sha256 "a08f20d6436b01a4d61f2a642f14b5f0dc49f219c24effd3e4e83e2be7ecd11f"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/beam-cloud/beta9/releases/download/cli-0.1.36/beta9-cli-0.1.36-linux-amd64.tar.gz"
    sha256 "547b2ceeadf034d7565aa6c7e54e1baf980898b29ab510e04670e5a18a7b1712"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/beam-cloud/beta9/releases/download/cli-0.1.36/beta9-cli-0.1.36-linux-arm64.tar.gz"
    sha256 "7b6204f827ca58f38372df037f5e0b220646e512a63d0d23659fcbcbf57003a0"
  else
    odie "Unsupported platform or architecture"
  end

  def install
    bin.install "beta9"
  end

  test do
    system "#{bin}/beta9", "--version"
  end
end
