# WARNING: This file is auto-generated by formula.py.
# Manual changes to this file will be overwritten the next time the file is generated.
# If you need to modify the contents, please update the source template or the generating script.

class Beta9 < Formula
  desc "The open-source serverless GPU container runtime."
  homepage "https://docs.beam.cloud/v2"
  license "AGPL-3.0"
  version "0.1.64"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/beam-cloud/beta9/releases/download/cli-0.1.64/beta9-0.1.64-darwin-amd64.tar.gz"
    sha256 "8ea0c87953a35f407c9c25dabd7ade00c3911b073a399b7bd5f6f747a877cd9e"
  elsif OS.mac? && Hardware::CPU.arm?
    url "https://github.com/beam-cloud/beta9/releases/download/cli-0.1.64/beta9-0.1.64-darwin-arm64.tar.gz"
    sha256 "007f53e32d88cba2fe40fd75d7abfd879f1a27efd2f67db988c91ee2c51fd570"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/beam-cloud/beta9/releases/download/cli-0.1.64/beta9-0.1.64-linux-amd64.tar.gz"
    sha256 "e08885fc8c25ce38082f98e3dc0d13716704b0196c4bdb24b47a34e2ee580831"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/beam-cloud/beta9/releases/download/cli-0.1.64/beta9-0.1.64-linux-arm64.tar.gz"
    sha256 "fe057f7a74c20dc2a6000a8127137adaa3295e918278467d5f96ebfaa60fee30"
  else
    odie "Unsupported platform or architecture"
  end

  def install
    bin.install "beta9"
  end

  test do
    system "#{bin}/beta9", "--version"
  end
end
