# WARNING: This file is auto-generated by formula.py.
# Manual changes to this file will be overwritten the next time the file is generated.
# If you need to modify the contents, please update the source template or the generating script.

class Kustomize < Formula
  desc "The open-source serverless GPU container runtime."
  homepage "https://docs.beam.cloud/v2"
  license "AGPL-3.0"
  version "v5.4.2"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v5.4.2/kustomize_v5.4.2_darwin_amd64.tar.gz"
    sha256 "d1dadf6d51058cdda6470344c95767e1c283cc5a36d5019eb32f8e43e63bd0df"
  elsif OS.mac? && Hardware::CPU.arm?
    url "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v5.4.2/kustomize_v5.4.2_darwin_arm64.tar.gz"
    sha256 "9b7da623cb40542f2dd220fa31d906d9254759b4e27583706e4e846fccba9fab"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v5.4.2/kustomize_v5.4.2_linux_amd64.tar.gz"
    sha256 "881c6e9007c7ea2b9ecc214d13f4cdd1f837635dcf4db49ce4479898f7d911a3"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v5.4.2/kustomize_v5.4.2_linux_arm64.tar.gz"
    sha256 "175af88af8a7d8d7d6b1f26659060950f0764d00b9979b4e11b61b8b212b7c22"
  else
    odie "Unsupported platform or architecture"
  end

  def install
    bin.install "kustomize"
  end

  test do
    system "#{bin}/kustomize", "--version"
  end
end
